# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Kyle van de Langemheen"
weight = 1

[nl]
languageName = "Nederlands"
languagedirection = "ltr"
title = "Kyle van de Langemheen"
weight = 2

[de]
languageName = "Deutsch"
languagedirection = "ltr"
title = "Kyle van de Langemheen"
weight = 3