# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub: kylevdlangemheen"
url = "https://github.com/KylevdLangemheen"

[social.params]
icon = "brand-github"

[[social]]
identifier = "linkedin"
name = "Linked-In: kylevdlangemheen"
url = "https://www.linkedin.com/in/kylevdlangemheen/"

[social.params]
icon = "brand-linkedin"
